### PR TITLE
FIX Travis tests to work on PRs

### PR DESCRIPTION
**Pull request by dhensby**
At the moment the travis script isn't meant for PRs, this change will allow us to run tests on PRs and publish the binary on merge.

### CODE REVIEW

**Comment by sminnee** [comment]
What happens if you upload a feature branch to this repo? I think that we only want to run this code on the master branch, rather than suppress it only for feature branch builds. Is that right?

**Comment by dhensby** [comment]
@sminnee that's a good point - yes, if a feature branch is created travis will currently build to gh-pages

we can use `$TRAVIS_BRANCH` for determining the branch - this needs to be used in conjunction with the pull request test too

From https://docs.travis-ci.com/user/environment-variables/ :

> For builds not triggered by a pull request this is the name of the branch currently being built; whereas for builds triggered by a pull request this is the name of the branch targeted by the pull request (in many cases this will be master).

**Comment by sminnee** [comment]
So these conditionals should be probably be ` [ "${TRAVIS_PULL_REQUEST}" = "false" -a "${TRAVIS_BRANCH}" = "master" ] ` then?

**Comment by dhensby** [comment]
Yep

**Comment by sminnee** [comment]
I added my suggestion as a 2nd commit.

**Pull request merged**
