### PR TITLE
Allow the ssh private key specified

### PR DESCRIPTION
**Pull request by mikenz**
Allow the SSH Identity file/private key to be passed in as a command line parameter to 'save' and 'load'.

### CODE REVIEW

**Comment by dhensby** [comment]
Looks cool. 

Side note: You know you can use ~.ssh/config locally to assign different keys to different hosts without the need for a flag? See http://nerderati.com/2011/03/17/simplify-your-life-with-an-ssh-config-file/ for some examples 

Not blocking this, just a comment.

**Comment by mikenz** [comment]
Yep. Two reasons I found this the prefered option here:
- all servers are in an AWS autoscaling group so the ip address of the remote server is almost always going to be different each time
- I didn't want a big list of servers I'm trying to protect and the keys to access them :-)

**Comment by dhensby** [comment]
I'm fairly happy - @sminnee ?

**Comment by dhensby** [comment]
Thanks

**Pull request merged**
