### PR TITLE
ss4 compatibility

### PR DESCRIPTION
**Pull request by anselmdk**

### CODE REVIEW

**Comment by dhensby** [comment]
Perhaps update the error message to be a bit more simple "Couldn't locate framework's Core.php" ?

**Comment by anselmdk** [comment]
Happy to do that, but what about doing that in a separate pull request, as it has no impact on the ss4 compatibility.

**Comment by dhensby** [comment]
The message says: 

>"No framework/core/Core.php or sapphire/core/Core.php included in project.  Perhaps " . BASE_PATH . " is not a SilverStripe project?\n";

So you should probably be updating that in this PR

**Comment by anselmdk** [comment]
You're right, I'll look into that.

**Comment by anselmdk** [comment]
@dhensby I've now simplified the error message and added a few inline comments so you know which SilverStripe version the sniffer is trying to sniff.

**Comment by dhensby** [comment]
Thanks

**Pull request merged**
